import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Brand colours (match the app) ───────────────────────────────────────────
const MAROON      = [122, 28,  46];
const MAROON_DARK = [79,  15,  28];
const COTTON      = [245, 242, 237];
const BLUE_JEANS  = [68,  92,  112];
const SOFT_GREEN  = [115, 130, 98];
const BUTTER      = [240, 204, 127];
const SUN_ORANGE  = [221, 139, 92];
const WHITE       = [255, 255, 255];
const TEXT        = [44,  26,  31];
const MUTED       = [138, 122, 114];
const SWEET_TAFFY = [233, 201, 216];
const SPA_BLUE    = [209, 225, 224];

// ─── Helpers ──────────────────────────────────────────────────────────────────
const W = 210; // A4 width mm
const H = 297; // A4 height mm
const PAD = 16;

function drawPageBorder(doc) {
  doc.setDrawColor(...MAROON);
  doc.setLineWidth(0.4);
  doc.rect(6, 6, W - 12, H - 12);
}

function drawHeader(doc, title, pageNum) {
  // Top bar
  doc.setFillColor(...MAROON_DARK);
  doc.rect(0, 0, W, 14, "F");

  // Accent stripe
  doc.setFillColor(...MAROON);
  doc.rect(0, 14, W, 2, "F");

  // Brand name left
  doc.setTextColor(...WHITE);
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "bold");
  doc.text("PRODUCT INSIGHT ANALYZER", PAD, 9);

  // Page title center
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.text(title.toUpperCase(), W / 2, 9, { align: "center" });

  // Page number right
  doc.text(`PAGE ${pageNum}`, W - PAD, 9, { align: "right" });
}

function drawFooter(doc) {
  const y = H - 10;
  doc.setFillColor(...MAROON);
  doc.rect(0, H - 14, W, 14, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Product Insight Analyzer  ·  Confidential", PAD, y);
  doc.text(new Date().toLocaleDateString("en-GB", { day:"2-digit", month:"short", year:"numeric" }), W - PAD, y, { align: "right" });
}

function sectionTitle(doc, text, y, accentColor = MAROON) {
  // Left accent bar
  doc.setFillColor(...accentColor);
  doc.rect(PAD, y - 4, 3, 6, "F");

  doc.setTextColor(...accentColor);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(text, PAD + 6, y);

  // Underline
  doc.setDrawColor(...accentColor);
  doc.setLineWidth(0.25);
  doc.line(PAD + 6, y + 2, W - PAD, y + 2);
}

function infoBox(doc, text, y, bgColor = COTTON, textColor = TEXT) {
  const lines = doc.splitTextToSize(text, W - PAD * 2 - 12);
  const boxH  = lines.length * 5.5 + 10;
  doc.setFillColor(...bgColor);
  doc.roundedRect(PAD, y, W - PAD * 2, boxH, 2, 2, "F");
  doc.setDrawColor(...MUTED);
  doc.setLineWidth(0.15);
  doc.roundedRect(PAD, y, W - PAD * 2, boxH, 2, 2, "S");
  doc.setTextColor(...textColor);
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.text(lines, PAD + 6, y + 7);
  return y + boxH + 6;
}

function statBox(doc, label, value, x, y, w, accentColor) {
  doc.setFillColor(...WHITE);
  doc.roundedRect(x, y, w, 20, 2, 2, "F");
  doc.setFillColor(...accentColor);
  doc.rect(x, y, 3, 20, "F");
  doc.setDrawColor(...MUTED);
  doc.setLineWidth(0.15);
  doc.roundedRect(x, y, w, 20, 2, 2, "S");

  doc.setTextColor(...MUTED);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text(label.toUpperCase(), x + 6, y + 7);

  doc.setTextColor(...TEXT);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(String(value), x + 6, y + 15);
}

// ─── Main export ──────────────────────────────────────────────────────────────
export const generatePDF = async (data, datasetName) => {
  try {
    if (!data) { alert("No data available"); return; }

    const doc  = new jsPDF({ unit: "mm", format: "a4" });
    const title = (data.best_product && data.best_product !== "Single Product Dataset")
      ? data.best_product
      : datasetName;

    // ══════════════════════════════════════════════════════════════════════════
    // PAGE 1 — COVER
    // ══════════════════════════════════════════════════════════════════════════
    drawPageBorder(doc);

    // Hero band
    doc.setFillColor(...MAROON_DARK);
    doc.rect(0, 0, W, 90, "F");

    // Decorative accent lines
    doc.setFillColor(...MAROON);
    doc.rect(0, 85, W, 5, "F");
    doc.setFillColor(...SUN_ORANGE);
    doc.rect(0, 87, W, 1.5, "F");

    // Logo/brand area
    doc.setTextColor(...WHITE);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("PRODUCT INSIGHT ANALYZER", W / 2, 30, { align: "center" });

    // Title
    doc.setFontSize(26);
    doc.setFont("helvetica", "bold");
    doc.text("Product Insight", W / 2, 52, { align: "center" });
    doc.setTextColor(...SUN_ORANGE);
    doc.text("Report", W / 2, 64, { align: "center" });

    // Tagline
    doc.setTextColor(210, 200, 200);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Powered by AI  ·  Data-Driven Decisions", W / 2, 76, { align: "center" });

    // Dataset name badge
    const badgeY = 100;
    doc.setFillColor(...COTTON);
    doc.roundedRect(PAD, badgeY, W - PAD * 2, 18, 3, 3, "F");
    doc.setFillColor(...MAROON);
    doc.rect(PAD, badgeY, 4, 18, "F");
    doc.setTextColor(...MUTED);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "bold");
    doc.text("DATASET", PAD + 10, badgeY + 7);
    doc.setTextColor(...TEXT);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(title, PAD + 10, badgeY + 14);

    // Summary stats row
    if (data.dataset_summary) {
      const s    = data.dataset_summary;
      const boxW = (W - PAD * 2 - 9) / 4;
      const bx   = PAD;
      const by   = 128;

      statBox(doc, "Total Reviews",    s.total_reviews,          bx,              by, boxW, BLUE_JEANS);
      statBox(doc, "Avg Rating",       `${s.average_rating} / 5`, bx + boxW + 3,   by, boxW, BUTTER);
      statBox(doc, "Positive",         `${s.positive_percent}%`, bx + (boxW+3)*2, by, boxW, SOFT_GREEN);
      statBox(doc, "Top Issue",        s.top_issue,              bx + (boxW+3)*3, by, boxW, MAROON);
    }

    // AI Summary box
    const sumY = 162;
    sectionTitle(doc, "AI Summary", sumY, MAROON);

    const summary = `This dataset contains ${data.dataset_summary?.total_reviews} reviews with an average rating of ${data.dataset_summary?.average_rating}. Around ${data.dataset_summary?.positive_percent}% of users are satisfied. The major issue identified is "${data.dataset_summary?.top_issue}".`;
    infoBox(doc, summary, sumY + 8, COTTON);

    // Footer
    drawFooter(doc);

    // ══════════════════════════════════════════════════════════════════════════
    // PAGE 2 — CHARTS
    // ══════════════════════════════════════════════════════════════════════════
    doc.addPage();
    drawPageBorder(doc);
    drawHeader(doc, "Distribution Analysis", 2);
    drawFooter(doc);

    const canvases = document.querySelectorAll("canvas");

    if (canvases.length >= 1) {
      sectionTitle(doc, "Rating Distribution", 26, BLUE_JEANS);
      const ratingImg = canvases[0].toDataURL("image/png", 1.0);
      // Chart bg card
      doc.setFillColor(...SPA_BLUE);
      doc.roundedRect(PAD, 32, W - PAD * 2, 88, 3, 3, "F");
      doc.addImage(ratingImg, "PNG", PAD + 4, 34, W - PAD * 2 - 8, 84);
    }

    if (canvases.length >= 2) {
      sectionTitle(doc, "Sentiment Distribution", 130, SOFT_GREEN);
      const sentImg = canvases[1].toDataURL("image/png", 1.0);
      doc.setFillColor(...COTTON);
      doc.roundedRect(PAD, 136, W - PAD * 2, 88, 3, 3, "F");
      doc.addImage(sentImg, "PNG", PAD + 4, 138, W - PAD * 2 - 8, 84);
    }

    // ══════════════════════════════════════════════════════════════════════════
    // PAGE 3 — ISSUES TABLE
    // ══════════════════════════════════════════════════════════════════════════
    doc.addPage();
    drawPageBorder(doc);
    drawHeader(doc, "Detected Issues", 3);
    drawFooter(doc);

    sectionTitle(doc, "Detected Issues", 26, MAROON);

    // Sort issues by count descending
    const sortedIssues = [...data.issues].sort((a, b) => b.count - a.count);
    const maxCount = sortedIssues[0]?.count || 1;

    autoTable(doc, {
      head: [["#", "Issue", "Count", "Share"]],
      body: sortedIssues.map((item, i) => [
        i + 1,
        item.issue,
        item.count.toLocaleString(),
        `${((item.count / data.dataset_summary?.total_reviews) * 100).toFixed(1)}%`,
      ]),
      startY: 32,
      margin: { left: PAD, right: PAD },
      styles: {
        fontSize: 10,
        cellPadding: 4,
        font: "helvetica",
        textColor: TEXT,
      },
      headStyles: {
        fillColor: MAROON_DARK,
        textColor: WHITE,
        fontStyle: "bold",
        fontSize: 9,
        cellPadding: 5,
      },
      alternateRowStyles: {
        fillColor: SWEET_TAFFY,
      },
      columnStyles: {
        0: { cellWidth: 10, halign: "center", textColor: MUTED },
        1: { cellWidth: "auto", fontStyle: "normal" },
        2: { cellWidth: 22, halign: "right", fontStyle: "bold", textColor: MAROON },
        3: { cellWidth: 20, halign: "right", textColor: BLUE_JEANS },
      },
      didDrawCell: (hookData) => {
        // Draw a mini bar in the Count column header row area
        if (hookData.section === "body" && hookData.column.index === 2) {
          const barW = (sortedIssues[hookData.row.index]?.count / maxCount) * 15;
          doc.setFillColor(...MAROON);
          doc.rect(
            hookData.cell.x + hookData.cell.width - barW - 1,
            hookData.cell.y + hookData.cell.height - 2.5,
            barW, 1.2, "F"
          );
        }
      },
      tableLineColor: MUTED,
      tableLineWidth: 0.1,
    });

    // ══════════════════════════════════════════════════════════════════════════
    // PAGE 4 — RECOMMENDATIONS
    // ══════════════════════════════════════════════════════════════════════════
    doc.addPage();
    drawPageBorder(doc);
    drawHeader(doc, "AI Recommendations", 4);
    drawFooter(doc);

    sectionTitle(doc, "AI Recommendations", 26, SOFT_GREEN);

    let recY = 38;
    data.recommendations.forEach((rec, i) => {
      // Alternating card background
      const bg = i % 2 === 0 ? [232, 237, 228] : WHITE;
      const lines   = doc.splitTextToSize(rec, W - PAD * 2 - 22);
      const cardH   = lines.length * 5.5 + 12;

      doc.setFillColor(...bg);
      doc.roundedRect(PAD, recY, W - PAD * 2, cardH, 2, 2, "F");

      // Green left accent
      doc.setFillColor(...SOFT_GREEN);
      doc.rect(PAD, recY, 3, cardH, "F");

      // Number badge
      doc.setFillColor(...SOFT_GREEN);
      doc.circle(PAD + 10, recY + cardH / 2, 4, "F");
      doc.setTextColor(...WHITE);
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "bold");
      doc.text(String(i + 1), PAD + 10, recY + cardH / 2 + 2.5, { align: "center" });

      // Rec text
      doc.setTextColor(...TEXT);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(lines, PAD + 18, recY + 7);

      recY += cardH + 5;
    });

    // ══════════════════════════════════════════════════════════════════════════
    // SAVE
    // ══════════════════════════════════════════════════════════════════════════
    doc.save(`${title}_Report.pdf`);

  } catch (err) {
    console.error(err);
    alert("PDF generation failed: " + err.message);
  }
};